type Query {
  "Loads cars and their identifiers for reduced object type testing"
  GetCarWithScalarId(
    "The car's ID"
    id: ID!
  ): CarWithScalarId
}

type CarWithScalarId {
  id: ID!
  name: String!
}
