type Query {
  "Generates a list with wrapped sub-lists using an ArrayIterator instance"
  GetPetOwners: [PetOwner!]
}

type PetOwner {
  person: Person!
  pets: [Pet!]!
}

type Person {
  name: String!

  "SHA256 hash of the Persons's name"
  nameHashed: String!

  isCelebrity: Boolean!
}

type Pet {
  name: String!
}
