type Query {
  "Allows listing all users and uses an iterator internally"
  GetUsersUsingIterators: [User]
}

type User {
  "The user ID of this entity"
  id: Int!

  person: Person!
  type: UserType!
}

type Person {
  name: String!

  "SHA256 hash of the Persons's name"
  nameHashed: String!

  isCelebrity: Boolean!
}

enum UserType {
  "A normal user without any special rights"
  NormalUser

  "An admin user with the right to rule the world"
  Admin
}
