name: PHP Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ "8.2", "8.3" ]
        composer: [ "" ]

    steps:
      - name: Checkout
        uses: actions/checkout@4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress --no-suggest --no-interaction ${{ matrix.composer }}

      - name: Run Tests
        run: vendor/bin/phpunit --testdox